config/routes.rb
Rails.application.routes.draw do
  resources :courses
  root 'courses#index'

end

app/models/course.rb
class Course < ActiveRecord::Base
#	mount_uploader :picture, PictureUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:title, :duration, :price, :picture, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def title(page_title)
	  content_for(:title) { page_title }
	end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<div class="x_content">
  <br>
<div class="form-horizontal form-label-left" >
  <%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-group">
      <%= f.label :title, :class => 'control-label col-md-3 col-sm-3 col-xs-12' %>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.text_field :title, :class => 'form-control col-md-7 col-xs-12' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :duration, :class => 'control-label col-md-3 col-sm-3 col-xs-12' %>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.text_field :duration, :class => 'form-control col-md-7 col-xs-12' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :price, :class => 'control-label col-md-3 col-sm-3 col-xs-12' %>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.text_field :price, :class => 'form-control col-md-7 col-xs-12' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :picture, :class => 'control-label col-md-3 col-sm-3 col-xs-12' %>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.file_field :picture, :class => 'form-control col-md-7 col-xs-12' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :description, :class => 'control-label col-md-3 col-sm-3 col-xs-12' %>
      <div class="col-md-6 col-sm-6 col-xs-12">
        <%= f.text_area :description, :class => 'form-control col-md-7 col-xs-12' %>
      </div>
    </div>

    <div class="ln_solid"></div>
    <div class="form-group">
      <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
        <%= f.submit :class => 'btn btn-success' %>
      </div>
    </div>

  </div>
  <% end %>
</div>

app/views/courses/edit.html.erb
<div class="row x_title">
  <div class="col-md-6"> 
  <h3>Editing Course</h3>
    </div>
</div>
<%= render 'form' %>

<%= link_to 'Show', @course, :class => 'btn btn-primary' %>
<%= link_to 'Back', courses_path, :class => 'btn btn-default' %>
<%= link_to 'Destroy this course', @course, :class => 'btn btn-danger btn-sm pull-right', method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row x_title">
  <div class="col-md-6"> 
  <h3>Listing Courses <small><%= link_to 'New Course', new_course_path, :class => 'btn btn-success' %>
</small></h3>
    </div>
</div>

<div class="row">

<% @courses.each do |course| %>
<div class="col-md-4 col-sm-4 col-xs-12">
            <div class="x_panel tile fixed_height_400">
              <div class="x_title">
                <h2><%= link_to course.title, course %></h2>
                <div class="clearfix"></div>
              </div>
              <div class="x_content">
              <h4>Duração: <%= course.duration %></h4>
              Preço: <%= course.price %><br>
              <%= image_tag course.picture_url(:thumb) if course.picture? %><br>
              <blockquote><%= course.description %></blockquote>
              <br>
              <div>
              <%= link_to 'Show', course, :class => 'btn btn-primary btn-sm' %>
              <%= link_to 'Edit', edit_course_path(course), :class => 'btn btn-warning btn-sm' %>
              
              </div>
              </div>

            </div>

    </div>
    <% end %>
</div>

  

app/views/courses/new.html.erb
<div class="row x_title">
	<div class="col-md-6"> 
	<h3>New Course <small>Create a new course</small></h3>
    </div>
</div>
<%= render 'form' %>

<%= link_to 'Back', courses_path, :class => 'btn btn-default' %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row x_title">
  <div class="col-md-6"> 
  <h3><%= @course.title %></h3>
    </div>
</div>

<blockquote><%= @course.description %></blockquote>



<p>
  <strong>Duration:</strong>
  <%= @course.duration %>
</p>

<p>
  <strong>Price:</strong>
  <%= @course.price %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@course.picture_url, :width => 600) if @course.picture.present? %>
</p>

<%= link_to 'Edit', edit_course_path(@course), :class => 'btn btn-warning btn-sm' %>
<%= link_to 'Back', @courses_path, :class => 'btn btn-default' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MeuAVA</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="nav-md">

 <div class="container body">


    <div class="main_container">

      <div class="col-md-3 left_col">
        <div class="left_col scroll-view">

          <div class="navbar nav_title" style="border: 0;">
            <%= link_to 'MeuAVA', root_path, :class => 'site_title text-center' %>
          </div>

          <div class="clearfix"></div>
          <!-- menu prile quick info -->
          <div class="profile">
            <div class="profile_pic">
              <img src="https://lh3.googleusercontent.com/-q7ljnQMvzJY/AAAAAAAAAAI/AAAAAAAABeA/EkhLjZ5Ep2E/s180-c-k-no/photo.jpg" alt="..." class="img-circle profile_img">
            </div>
            <div class="profile_info">
              <span>Welcome,</span>
              <h2>Leandro Macedo</h2>
            </div>
          </div>
          <!-- /menu prile quick info -->

          <br />

          <!-- sidebar menu -->
          <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">

            <div class="menu_section">
              <h3>PERFIL</h3>
              <ul class="nav side-menu">
                <li><%= link_to 'Home', root_path %></li>
                <li><%= link_to 'Courses', courses_path %></li>
                <li><%= link_to 'Create New Course', new_course_path %></li>
              </ul>
            </div>
            
          </div>
          <!-- /sidebar menu -->

          <!-- /menu footer buttons -->
          <!-- 
          <div class="sidebar-footer hidden-small">
            <a data-toggle="tooltip" data-placement="top" title="Settings">
              <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="FullScreen">
              <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Lock">
              <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Logout">
              <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
            </a>
          </div>
          -->
          <!-- /menu footer buttons -->
        </div>
      </div>

      <!-- top navigation -->
      <div class="top_nav">

        <div class="nav_menu">
          <nav class="" role="navigation">
            <div class="nav toggle">
              <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>

            <ul class="nav navbar-nav navbar-right">
              <li class="">
                <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                  <img src="https://lh3.googleusercontent.com/-q7ljnQMvzJY/AAAAAAAAAAI/AAAAAAAABeA/EkhLjZ5Ep2E/s180-c-k-no/photo.jpg" alt="">Leandro Macedo
                  <span class=" fa fa-angle-down"></span>
                </a>
                <ul class="dropdown-menu dropdown-usermenu animated fadeInDown pull-right">
                  <li><a href="javascript:;">  Profile</a>
                  </li>
                  <li>
                    <a href="javascript:;">
                      <span class="badge bg-red pull-right">50%</span>
                      <span>Settings</span>
                    </a>
                  </li>
                  <li>
                    <a href="javascript:;">Help</a>
                  </li>
                  <li><a href="login.html"><i class="fa fa-sign-out pull-right"></i> Log Out</a>
                  </li>
                </ul>
              </li>

              <li role="presentation" class="dropdown">
                <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
                  <i class="fa fa-envelope-o"></i>
                  <span class="badge bg-green">6</span>
                </a>
                <ul id="menu1" class="dropdown-menu list-unstyled msg_list animated fadeInDown" role="menu">
                  <li>
                    <a>
                      <span class="image">
                                        <img src="images/img.jpg" alt="Profile Image" />
                                    </span>
                      <span>
                                        <span>John Smith</span>
                      <span class="time">3 mins ago</span>
                      </span>
                      <span class="message">
                                        Film festivals used to be do-or-die moments for movie makers. They were where...
                                    </span>
                    </a>
                  </li>
                  <li>
                    <a>
                      <span class="image">
                                        <img src="images/img.jpg" alt="Profile Image" />
                                    </span>
                      <span>
                                        <span>John Smith</span>
                      <span class="time">3 mins ago</span>
                      </span>
                      <span class="message">
                                        Film festivals used to be do-or-die moments for movie makers. They were where...
                                    </span>
                    </a>
                  </li>
                  <li>
                    <a>
                      <span class="image">
                                        <img src="images/img.jpg" alt="Profile Image" />
                                    </span>
                      <span>
                                        <span>John Smith</span>
                      <span class="time">3 mins ago</span>
                      </span>
                      <span class="message">
                                        Film festivals used to be do-or-die moments for movie makers. They were where...
                                    </span>
                    </a>
                  </li>
                  <li>
                    <a>
                      <span class="image">
                                        <img src="images/img.jpg" alt="Profile Image" />
                                    </span>
                      <span>
                                        <span>John Smith</span>
                      <span class="time">3 mins ago</span>
                      </span>
                      <span class="message">
                                        Film festivals used to be do-or-die moments for movie makers. They were where...
                                    </span>
                    </a>
                  </li>
                  <li>
                    <div class="text-center">
                      <a href="inbox.html">
                        <strong>See All Alerts</strong>
                        <i class="fa fa-angle-right"></i>
                      </a>
                    </div>
                  </li>
                </ul>
              </li>

            </ul>
          </nav>
        </div>

      </div>
      <!-- /top navigation -->


      <!-- page content -->
      <div class="right_col" role="main">

        <!-- top tiles -->
        <div class="row tile_count">
          <div class="animated flipInY col-md-2 col-sm-4 col-xs-4 tile_stats_count">
            <div class="left"></div>
            <div class="right">
              <span class="count_top"><i class="fa fa-user"></i> Total Users</span>
              <div class="count">2500</div>
              <span class="count_bottom"><i class="green">4% </i> From last Week</span>
            </div>
          </div>
          <div class="animated flipInY col-md-2 col-sm-4 col-xs-4 tile_stats_count">
            <div class="left"></div>
            <div class="right">
              <span class="count_top"><i class="fa fa-clock-o"></i> Average Time</span>
              <div class="count">123.50</div>
              <span class="count_bottom"><i class="green"><i class="fa fa-sort-asc"></i>3% </i> From last Week</span>
            </div>
          </div>
          <div class="animated flipInY col-md-2 col-sm-4 col-xs-4 tile_stats_count">
            <div class="left"></div>
            <div class="right">
              <span class="count_top"><i class="fa fa-user"></i> Total Males</span>
              <div class="count green">2,500</div>
              <span class="count_bottom"><i class="green"><i class="fa fa-sort-asc"></i>34% </i> From last Week</span>
            </div>
          </div>
          <div class="animated flipInY col-md-2 col-sm-4 col-xs-4 tile_stats_count">
            <div class="left"></div>
            <div class="right">
              <span class="count_top"><i class="fa fa-user"></i> Total Females</span>
              <div class="count">4,567</div>
              <span class="count_bottom"><i class="red"><i class="fa fa-sort-desc"></i>12% </i> From last Week</span>
            </div>
          </div>
          <div class="animated flipInY col-md-2 col-sm-4 col-xs-4 tile_stats_count">
            <div class="left"></div>
            <div class="right">
              <span class="count_top"><i class="fa fa-user"></i> Total Collections</span>
              <div class="count">2,315</div>
              <span class="count_bottom"><i class="green"><i class="fa fa-sort-asc"></i>34% </i> From last Week</span>
            </div>
          </div>
          <div class="animated flipInY col-md-2 col-sm-4 col-xs-4 tile_stats_count">
            <div class="left"></div>
            <div class="right">
              <span class="count_top"><i class="fa fa-user"></i> Total Connections</span>
              <div class="count">7,325</div>
              <span class="count_bottom"><i class="green"><i class="fa fa-sort-asc"></i>34% </i> From last Week</span>
            </div>
          </div>

        </div>
        <!-- /top tiles -->

        <div class="row">
          <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="dashboard_graph">

              <div class="col-md-12 col-sm-12 col-xs-12">
                <div id="placeholder33" style="height: 260px; display: none" class="demo-placeholder"></div>
                <div style="width: 100%;">
                    <%= yield %>
                </div>
              </div>

              <div class="clearfix"></div>
            </div>
          </div>

        </div>
        <br />

        


        
        <!-- footer content -->

        <footer>
          <div class="copyright-info">
            <p class="pull-right">Desenvolvido por. <a href="https://leandromacedo.com">Leandro Macedo</a>  
            </p>
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
      </div>
      <!-- /page content -->

    </div>

  </div>

  <div id="custom_notifications" class="custom-notifications dsp_none">
    <ul class="list-unstyled notifications clearfix" data-tabbed_notifications="notif-group">
    </ul>
    <div class="clearfix"></div>
    <div id="notif-group" class="tabbed_notifications"></div>
  </div>

</body>
</html>